# Generated by Django 2.1.5 on 2019-05-10 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_engine', '0005_account_balance_account'),
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('being_credit_operation', 'En financiamiento'), ('financed', 'Financiada'), ('requestor_payment', 'Solicitante Pagado'), ('collecting_instalments', 'Pago y Cobranza de Cuotas'), ('completed', 'Completada'), ('canceled', 'Cancelada'), ('default', 'Cobranza Judicial')], default='being_credit_operation', max_length=20)),
                ('financing_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('requestor_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requestor_account', to='account_engine.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
