# Generated by Django 2.1.5 on 2019-05-08 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_engine', '0002_virtualaccountdeposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualaccountdeposit',
            name='journal',
        ),
        migrations.AlterField(
            model_name='virtualaccountdeposit',
            name='bank_account_origin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destiny_posting', to='account_engine.Posting'),
        ),
        migrations.AlterField(
            model_name='virtualaccountdeposit',
            name='virtual_account_destiny',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origin_posting', to='account_engine.Posting'),
        ),
    ]
