# Generated by Django 2.1.5 on 2019-05-09 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_engine', '0003_auto_20190508_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualaccountdeposit',
            name='bank_account_origin',
        ),
        migrations.RemoveField(
            model_name='virtualaccountdeposit',
            name='virtual_account_destiny',
        ),
        migrations.AddField(
            model_name='virtualaccountdeposit',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='account_engine.Account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualaccountdeposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='virtualaccountdeposit',
            name='asset_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='account_engine.AssetType'),
        ),
        migrations.AddField(
            model_name='virtualaccountdeposit',
            name='deposit_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualaccountdeposit',
            name='real_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='account_engine.BankAccount'),
            preserve_default=False,
        ),
    ]
