# Generated by Django 2.1.5 on 2019-06-04 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_engine', '0005_account_balance_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchTransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='batch_transaction',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='account_engine.BatchTransactionType'),
        ),
    ]
