# Generated by Django 2.1.5 on 2019-05-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_creditoperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditoperation',
            name='state',
            field=models.CharField(choices=[('being_credit_operation', 'En financiamiento'), ('financed', 'Financiada'), ('requestor_payment', 'Solicitante Pagado'), ('collecting_instalments', 'Pago y Cobranza de Cuotas'), ('completed', 'Completada'), ('canceled', 'Cancelada'), ('default', 'Cobranza Judicial')], default='being_credit_operation', max_length=30),
        ),
    ]
