# Generated by Django 2.1.5 on 2019-05-13 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_engine', '0005_account_balance_account'),
        ('credits', '0003_auto_20190510_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instalment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='creditoperation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='creditoperation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='creditoperation',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='creditoperation',
            name='account_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account_engine.Account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='creditoperation',
            name='requestor_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requestor_credits_operation', to='account_engine.Account'),
        ),
        migrations.AddField(
            model_name='instalment',
            name='credit_operation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='credits.CreditOperation'),
        ),
    ]
