# Generated by Django 2.1.5 on 2019-06-04 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0005_instalment_external_instalment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentcreditoperation',
            name='credits_operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='credits.CreditOperation'),
        ),
        migrations.AlterField(
            model_name='investmentcreditoperation',
            name='investment_cost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='credits.CreditsCost'),
        ),
    ]
