# Generated by Django 2.1.5 on 2019-06-04 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_engine', '0005_account_balance_account'),
        ('credits', '0006_auto_20190604_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary_name', models.CharField(max_length=250)),
                ('document_number', models.IntegerField()),
                ('transfer_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('paysheet_line_type', models.CharField(max_length=50)),
                ('bank_code', models.IntegerField()),
                ('state', models.CharField(choices=[('pending', 'Enviado a tesoreria'), ('completed', 'Confirmado por tesoreria')], default='pending', max_length=30)),
                ('destination_account', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='destination_account', to='account_engine.BankAccount')),
                ('journal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='account_engine.Journal')),
                ('origin_account', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='origin_account', to='account_engine.BankAccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
