# Generated by Django 2.1.5 on 2019-05-07 20:44

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('external_account_id', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_type', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account_number', models.IntegerField()),
                ('account_notification_email', models.EmailField(max_length=254)),
                ('bank_code', models.IntegerField()),
                ('account_bank_type', models.IntegerField()),
                ('account_holder_name', models.CharField(max_length=200)),
                ('account_holder_document_number', models.CharField(max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=150)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00000'), max_digits=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DWHBalanceAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance_account_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Instalment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gloss', models.TextField(max_length=350)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journals', to='account_engine.Batch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JournalTransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OperationAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account_engine.Account')),
                ('financing_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('account_engine.account',),
        ),
        migrations.AddField(
            model_name='posting',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account_engine.Account'),
        ),
        migrations.AddField(
            model_name='posting',
            name='asset_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='account_engine.AssetType'),
        ),
        migrations.AddField(
            model_name='posting',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postings', to='account_engine.Journal'),
        ),
        migrations.AddField(
            model_name='journal',
            name='journal_transaction',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='account_engine.JournalTransactionType'),
        ),
        migrations.AddField(
            model_name='dwhbalanceaccount',
            name='account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='account_engine.Account'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account_engine.Account'),
        ),
        migrations.AddField(
            model_name='account',
            name='external_account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account_engine.AccountType'),
        ),
        migrations.AddField(
            model_name='operationaccount',
            name='requester_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requestor', to='account_engine.Account'),
        ),
        migrations.AddField(
            model_name='instalment',
            name='operation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='account_engine.OperationAccount'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('external_account_id', 'external_account_type')},
        ),
    ]
