# Generated by Django 2.1.5 on 2019-05-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_engine', '0004_auto_20190509_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance_account',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
